# Generated by Django 4.0.1 on 2022-01-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournamentregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('team_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=150)),
                ('captain_name', models.CharField(max_length=150)),
                ('manager_name', models.CharField(max_length=150)),
                ('one_player', models.CharField(max_length=150)),
                ('two_player', models.CharField(max_length=150)),
                ('three_player', models.CharField(max_length=150)),
                ('four_player', models.CharField(max_length=150)),
                ('five_player', models.CharField(max_length=150)),
                ('six_player', models.CharField(max_length=150)),
                ('seven_player', models.CharField(max_length=150)),
                ('eight_player', models.CharField(max_length=150)),
                ('jersey_color', models.CharField(max_length=150)),
                ('coach_name', models.CharField(max_length=150)),
            ],
        ),
    ]
