# Generated by Django 4.0.3 on 2022-04-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
    ]
