# Generated by Django 4.0.3 on 2022-04-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_alter_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
    ]
