# Generated by Django 4.0.3 on 2022-04-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0019_customer_address_customer_age_alter_customer_avatar'),
        ('Booking', '0005_remove_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Shopping.customer'),
        ),
    ]
