# Generated by Django 4.0.3 on 2022-04-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
