# Generated by Django 4.0.1 on 2022-01-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
