# Generated by Django 4.0.1 on 2022-02-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
