# Generated by Django 4.0.1 on 2022-02-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0013_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
