# Generated by Django 4.0.1 on 2022-03-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0015_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='fullname',
        ),
    ]
