# Generated by Django 4.0.3 on 2022-04-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0017_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
