# Generated by Django 4.0.3 on 2022-04-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0019_customer_address_customer_age_alter_customer_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='avatar',
        ),
    ]
