# Generated by Django 4.0.3 on 2022-04-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0021_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(default='static/user.png', upload_to='static/UserProfile'),
        ),
    ]
