# Generated by Django 4.0.3 on 2022-04-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0029_customer_address_customer_age_customer_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
