# Generated by Django 4.0.3 on 2022-04-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0030_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
