# Generated by Django 4.0.3 on 2022-04-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0031_order_ordered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
